# Generated by Django 4.2.17 on 2024-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food', models.CharField(choices=[('BURGER', 'המבורגר'), ('HOTDOG', 'נקנקיה'), ('TOAST', 'סודוך')], max_length=100)),
                ('pay', models.CharField(choices=[('CASH', 'מזומן'), ('NOTE', 'שוברים')], max_length=100)),
            ],
        ),
    ]
