# Generated by Django 4.2.17 on 2024-12-23 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food', models.CharField(choices=[('BURGER', 'המבורגר'), ('HOTDOG', 'נקנקיה'), ('TOAST', 'סודוך')], max_length=100)),
                ('pay', models.CharField(choices=[('CASH', 'מזומן'), ('NOTE', 'שוברים')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RabbiOrderBurgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
                ('left', models.PositiveIntegerField(default=models.PositiveIntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='RabbiOrderHotdogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
                ('left', models.PositiveIntegerField(default=models.PositiveIntegerField())),
            ],
        ),
    ]
